language: python
python:
    - "2.7"
install: 
    - "pip install cython"
    - "pip install numpy"
    - "pip install scipy"
    - "pip install matplotlib"
    - "pip install docopt"
    - "pip install py"
    - "pip install pytest"
    - "pip install schema"
    - "pip install pandas"
    - "pip install seaborn"
    - "pip install six"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=piquant setup.py test"
after_success:
    coveralls
