language: python
python:
    - "2.7"
install: 
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install git+git://github.com/lweasel/ord-utils.git"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=ordutils setup.py test"
after_success:
    coveralls
